import AppKit
import Combine

@MainActor
final class ClipboardService: ObservableObject {
    @Published private(set) var entries: [ClipboardEntry] = []
    @Published var query = "" {
        didSet { reload() }
    }

    private let store: ClipboardStore
    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount
    private let deniedBundleIDs: Set<String> = [
        "com.1password.1password",
        "com.1password.1password7",
        "com.agilebits.onepassword7",
        "com.lastpass.LastPass",
        "com.bitwarden.desktop",
        "com.dashlane.dashlanephonefinal",
        "com.dashlane.dashlane"
    ]

    init(store: ClipboardStore = ClipboardStore()) {
        self.store = store
        reload()
    }

    func start() {
        guard timer == nil else { return }
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            Task { @MainActor in
                self?.pollPasteboard()
            }
        }
        timer?.tolerance = 0.2
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    func reload() {
        entries = store.entries(matching: query)
    }

    func delete(_ entry: ClipboardEntry) {
        store.deleteEntry(id: entry.id)
        reload()
    }

    func clear() {
        store.deleteAll()
        reload()
    }

    func applyRetention(maxEntries: Int, maxAgeDays: Int) {
        store.applyRetention(maxEntries: maxEntries, maxAgeDays: maxAgeDays)
        reload()
    }

    private func pollPasteboard() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        let types = pasteboard.types ?? []
        guard !types.contains(NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")),
              !types.contains(NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")) else {
            return
        }

        guard let text = pasteboard.string(forType: .string), text.utf8.count <= 1_048_576 else { return }
        let app = NSWorkspace.shared.frontmostApplication
        if let bundleID = app?.bundleIdentifier, deniedBundleIDs.contains(bundleID) {
            return
        }

        let defaults = UserDefaults.standard
        let maxEntries = defaults.integer(forKey: AppDefaults.clipboardMaxEntries)
        let maxAgeDays = defaults.integer(forKey: AppDefaults.clipboardMaxAgeDays)
        store.insert(
            content: text,
            sourceAppBundleID: app?.bundleIdentifier,
            sourceAppName: app?.localizedName,
            maxEntries: max(maxEntries, 1),
            maxAgeDays: max(maxAgeDays, 1)
        )
        reload()
    }
}
